apiVersion: skaffold/v1
kind: Config
metadata:
  name: test-micronaut-skaffold

build: {}

deploy:
  kubectl:
    manifests:
      - this_file_doesnt_exist_pick_a_profile

profiles:
  - name: dummy_profile
    build:
      local:
        push: false

      artifacts:
        - &pubArtifact
          context: .
          image: myapp-a
          jib:
            project: myapp-a
            args:
              - -DskipTests

        - &conArtifact
          context: .
          image: myapp-b
          jib:
            project: myapp-b
            args:
              - -DskipTests
    deploy:
      kubectl:
        manifests: &manifests
          - manifests/*.yaml

    # NOTE: if you run `skaffold dev --port-forward=true` then that sets up
    #       port-forwards for the service, and any configured portForward in YaML
    #       on the service is replaced by the auto-configured one. That's why
    #       these are creating port-forwards to the deployment.
    #
    portForward:
      # myapp-b
      - &pfConHTTP
        resourceType: deployment
        resourceName: myapp-b
        port: 8080
        localPort: 18080
      - &pfConDebug
        resourceType: deployment
        resourceName: myapp-b
        port: 5005
        localPort: 15005
      # myapp-a
      - &pfPubHTTP
        resourceType: deployment
        resourceName: myapp-a
        port: 8080
        localPort: 28080
      - &pfPubDebug
        resourceType: deployment
        resourceName: myapp-a
        port: 5005
        localPort: 25005

  - name: schristensen

    activation:
      - kubeContext: docker-desktop
        env: USER=schristensen
    build:
      local:
        push: false

      artifacts:
        - *pubArtifact
        - *conArtifact

    deploy:
      # always deploy to docker-desktop
      kubeContext: docker-desktop

      kubectl:
        manifests: *manifests

    portForward:
      # myapp-b
      - namespace: schristensen
        << : *pfConHTTP
      - namespace: schristensen
        << : *pfConDebug
      # myapp-a
      - namespace: schristensen
        << : *pfPubHTTP
      - namespace: schristensen
        << : *pfPubDebug
