apiVersion: skaffold/v1
kind: Config
metadata:
  name: test-micronaut-skaffold

build: {}

deploy:
  kubectl:
    manifests:
      - this_file_doesnt_exist_pick_a_profile

profiles:
  - name: dummy_profile
    build:
      local:
        push: false

      artifacts:
        - &artifactA
          context: .
          image: myapp-a
          jib:
            project: myapp-a
            args:
              - -DskipTests

        - &artifactB

          context: .
          image: myapp-b
          jib:
            project: myapp-b
            args:
              - -DskipTests
    deploy:
      kubectl:
        manifests: &manifests
          - manifests/*.yaml

    # NOTE: if you run `skaffold dev --port-forward=true` then that sets up
    #       port-forwards for the service, and any configured portForward in YaML
    #       on the service is replaced by the auto-configured one. That's why
    #       these are creating port-forwards to the deployment.
    #
    portForward:
      # myapp-b
      - &pfAHTTP
        resourceType: deployment
        resourceName: myapp-b
        port: 8080
        localPort: 18080
      - &pfADebug
        resourceType: deployment
        resourceName: myapp-b
        port: 5005
        localPort: 15005
      # myapp-a
      - &pfBHTTP
        resourceType: deployment
        resourceName: myapp-a
        port: 8080
        localPort: 28080
      - &pfBDebug
        resourceType: deployment
        resourceName: myapp-a
        port: 5005
        localPort: 25005

  - name: schristensen

    activation:
      - kubeContext: docker-desktop
        env: USER=schristensen
    build:
      local:
        push: false

      artifacts:
        - *artifactA
        - *artifactB


    deploy:
      # always deploy to docker-desktop
      kubeContext: docker-desktop

      kubectl:
        manifests: *manifests

    portForward:
      # myapp-b
      - namespace: schristensen
        << : *pfAHTTP
      - namespace: schristensen
        << : *pfADebug
      # myapp-a
      - namespace: schristensen
        << : *pfBHTTP
      - namespace: schristensen
        << : *pfBDebug

  - name: default

    activation:
      - kubeContext: docker-desktop
    build:
      local:
        push: false

      artifacts:
        - *artifactA
        - *artifactB


    deploy:
      # always deploy to docker-desktop
      kubeContext: docker-desktop

      kubectl:
        manifests: *manifests

    portForward:
      # myapp-b
      - namespace: default
        << : *pfAHTTP
      - namespace: default
        << : *pfADebug
      # myapp-a
      - namespace: default
        << : *pfBHTTP
      - namespace: default
        << : *pfBDebug
