---
apiVersion: v1
kind: Service
metadata:
  name: myapp-a
  labels:
    app: myapp-a
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: tcp-jvmdebug
      protocol: TCP
      name: tcp-jvmdebug
  selector:
    app: myapp-a
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-b
  labels:
    app: myapp-b
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 5005
      targetPort: tcp-jvmdebug
      protocol: TCP
      name: tcp-jvmdebug
  selector:
    app: myapp-b
